# Generated by Django 5.1 on 2024-08-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avocate',
            new_name='Advocate',
        ),
    ]
