# Generated by Django 5.1 on 2024-08-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_avocate_advocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
